-- AlterTable
ALTER TABLE "y7_gifs" ALTER COLUMN "size" DROP DEFAULT,
ALTER COLUMN "width" DROP DEFAULT,
ALTER COLUMN "height" DROP DEFAULT,
ALTER COLUMN "frames" DROP DEFAULT;

-- AlterTable
ALTER TABLE "y7_images" ALTER COLUMN "height" DROP DEFAULT,
ALTER COLUMN "size" DROP DEFAULT,
ALTER COLUMN "width" DROP DEFAULT;
