const languages = {
  so: 'af Soomaali',
  afr: 'Afrikaans',
  ar: 'العربية',
  egy: '𓂋𓏺𓈖 𓆎𓅓𓏏𓊖',
  arc: 'ܐܪܡܝܐ | ארמיא',
  hy: 'հայերեն',
  ast: 'asturianu',
  id: 'Bahasa Indonesia',
  ms: 'Bahasa Malaysia',
  bg: 'Български',
  bn: 'বাংলা',
  jv: 'Basa Jawa',
  be: 'беларуская',
  bos: 'Bosanski',
  br: 'Brezhoneg',
  ca: 'Català',
  ceb: 'Cebuano',
  cs: 'Čeština',
  chn: 'Chinuk Wawa',
  cy: 'Cymraeg',
  da: 'Dansk',
  de: 'Deutsch',
  et: 'eesti keel',
  el: 'Ελληνικά',
  en: 'English',
  ang: 'Englisċ',
  es: 'Español',
  eo: 'Esperanto',
  eu: 'Euskara',
  fa: 'فارسی',
  fil: 'Filipino',
  fr: 'Français',
  fur: 'Furlan',
  ga: 'Gaeilge',
  gd: 'Gàidhlig',
  gl: 'Galego',
  got: '𐌲𐌿𐍄𐌹𐍃𐌺𐌰',
  hak: '中文-客家话',
  ko: '한국어',
  hau: 'Hausa | هَرْشَن هَوْسَ',
  hi: 'हिन्दी',
  hr: 'Hrvatski',
  ia: 'Interlingua',
  zu: 'isiZulu',
  is: 'Íslenska',
  it: 'Italiano',
  he: 'עברית',
  kan: 'ಕನ್ನಡ',
  kat: 'ქართული',
  khm: 'ភាសាខ្មែរ',
  qkz: 'Khuzdul',
  sw: 'Kiswahili',
  ht: 'kreyòl ayisyen',
  ku: 'Kurdî | کوردی',
  kir: 'Кыргызча',
  fcs: 'Langue des signes québécoise',
  lv: 'Latviešu valoda',
  lb: 'Lëtzebuergesch',
  lt: 'Lietuvių kalba',
  la: 'Lingua latina',
  hu: 'Magyar',
  mk: 'македонски',
  ml: 'മലയാളം',
  mt: 'Malti',
  mnc: 'ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ',
  mr: 'मराठी',
  mik: 'Mikisúkî',
  mon: 'ᠮᠣᠩᠭᠣᠯ ᠪᠢᠴᠢᠭ᠌ | Монгол Кирилл үсэг',
  my: 'မြန်မာဘာသာ',
  nah: 'Nāhuatl',
  nan: '中文-闽南话 臺語',
  nl: 'Nederlands',
  ja: '日本語',
  no: 'Norsk',
  azj: 'Азәрбајҹан дили | آذربایجان دیلی',
  ce: 'Нохчийн мотт',
  ota: 'لسان عثمانى',
  ps: 'پښتو',
  nds: 'Plattdüütsch',
  pl: 'Polski',
  ptBR: 'Português brasileiro',
  ptPT: 'Português europeu',
  pa: 'ਪੰਜਾਬੀ',
  kaz: 'qazaqşa | қазақша',
  qya: 'Quenya',
  ro: 'Română',
  ru: 'Русский',
  sco: 'Sc',
  sq: 'Shqip',
  sjn: 'Sindarin',
  si: 'සිංහල',
  sk: 'Slovenčina',
  slv: 'Slovenščina',
  gem: 'Sprēkō Þiudiskō',
  sr: 'Српски',
  fi: 'Suomi',
  sv: 'Svenska',
  ta: 'தமிழ்',
  tel: 'తెలుగు',
  th: 'ไทย',
  tqx: 'Thermian',
  bod: 'བོད་སྐད་',
  vi: 'Tiếng Việt',
  cop: 'ϯⲙⲉⲧⲣⲉⲙⲛ̀ⲭⲏⲙⲓ',
  tlh: 'tlhIngan-Hol',
  qtp: 'toki pona',
  tsd: 'τσακώνικα',
  tr: 'Türkçe',
  uk: 'Українська',
  urd: 'اُردُو',
  uig: 'ئۇيغۇر تىلى',
  vol: 'Volapük',
  wuu: '中文-吴语',
  yi: 'יידיש',
  yua: 'maayaʼ tʼàan',
  yue: '中文-广东话 粵語',
  zh: '中文-普通话 國語'
};
export default languages;

export type Language = keyof typeof languages;
